_: let
  useAbsolutePaths = config:
    builtins.replaceStrings [
      "hwmon0"
      "hwmon1"
    ] [
      "/sys/devices/platform/coretemp.0/hwmon/hwmon[[:print:]]*"
      "/sys/devices/platform/dell_smm_hwmon/hwmon/hwmon[[:print:]]*"
    ]
    config;
in {
  hardware.fancontrol = {
    enable = true;
    config = useAbsolutePaths ''
      # Configuration file generated by pwmconfig, changes will be lost
      INTERVAL=10
      # DEVPATH=hwmon0=devices/platform/coretemp.0 hwmon1=devices/platform/dell_smm_hwmon
      # DEVNAME=hwmon0=coretemp hwmon1=dell_smm
      FCTEMPS=hwmon1/pwm2=hwmon0/temp2_input hwmon1/pwm1=hwmon0/temp2_input
      FCFANS=hwmon1/pwm2=hwmon1/fan2_input hwmon1/pwm1=hwmon1/fan1_input
      MINTEMP=hwmon1/pwm2=40 hwmon1/pwm1=40
      MAXTEMP=hwmon1/pwm2=60 hwmon1/pwm1=60
      MINSTART=hwmon1/pwm2=50 hwmon1/pwm1=50
      MINSTOP=hwmon1/pwm2=0 hwmon1/pwm1=0
      MAXPWM=hwmon1/pwm2=150 hwmon1/pwm1=150
    '';
  };

  # Generated by sensors-detect on Thu Oct 16 20:34:02 2025
  boot.kernelModules = ["coretemp" "f71882fg"];
}
