#!/usr/bin/env bash

RADEON9070_DIR=/sys/devices/pci0000:00/0000:00:03.1/0000:08:00.0/0000:09:00.0/0000:0a:00.0

# Set fan curve
echo "0 60 30" > $RADEON9070_DIR/gpu_od/fan_ctrl/fan_curve
echo "1 65 40" > $RADEON9070_DIR/gpu_od/fan_ctrl/fan_curve
echo "2 70 50" > $RADEON9070_DIR/gpu_od/fan_ctrl/fan_curve
echo "3 80 90" > $RADEON9070_DIR/gpu_od/fan_ctrl/fan_curve
echo "4 90 100" > $RADEON9070_DIR/gpu_od/fan_ctrl/fan_curve

# Set max GPU clock offset
echo "s -100" > $RADEON9070_DIR/pp_od_clk_voltage

# Set max power to 370W
echo "340000000" > $RADEON9070_DIR/hwmon/*/power1_cap

# Set power profile to 3D_FULL_SCREEN
echo "manual" > $RADEON9070_DIR/power_dpm_force_performance_level
echo "1" > $RADEON9070_DIR/pp_power_profile_mode

# Commit GPU clock
echo "c" > $RADEON9070_DIR/pp_od_clk_voltage

# Commit fan curve
echo "c" > $RADEON9070_DIR/gpu_od/fan_ctrl/fan_curve
