name: "CI/CD Pipeline"

on:
  push:
  pull_request:

jobs:
  pipeline:
    name: "CI/CD Pipeline"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: nixbuild/nix-quick-install-action@v30

    - name: Check formatting
      run: nix run .#alejandra -- -c .

    - name: Check linting
      run: nix run .#statix check . -- --ignore hosts/*/hardware-configuration.nix

    - name: Flake check
      run: nix flake check

    - name: Build dekstop
      uses: ./.github/actions/nixos-rebuild
      with:
        hostname: "desktop"

    - name: Build thinkpad
      uses: ./.github/actions/nixos-rebuild
      with:
        hostname: "thinkpad"
