name: "CI/CD Pipeline"

on:
  push:
  pull_request:

jobs:
  pipeline:
    name: "CI/CD Pipeline"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: nixbuild/nix-quick-install-action@v30
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: nix-community/cache-nix-action@v6
      with:
        primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
        restore-prefixes-first-match: nix-${{ runner.os }}-
    - run: nix flake check
